Username  = "tangyang"
Password  = ""
PublicKey = "/home/tangyang/.ssh/id_rsa"

[hosts.default]
Hosts     = [
    "127.0.0.[1-5]:22",
    "127.0.0.[2-5]",
    "127.0.0.6",
    "127.0.0.7:223",
]

[hosts.test]
Hosts     = [
    "127.0.0.2",
]
